### ISSUE TITLE
Disable (comment out) 'unwanted' actions

### ISSUE THREAD

**Issue by gdavydov** [gdavydov/museum-collections#14]
For visitor modify "Selected Items" and disable
Copy To
Move To
Statrt Workflow
Delete

For other users (except system admin (superuser) disable
Statrt Workflow

**Comment by gdavydov** [comment]
https://forums.alfresco.com/forum/installation-upgrades-configuration-integration/configuration/how-disable-start-workflow

**Comment by DmitryAlexandrov** [comment]
Seems like commit https://github.com/gdavydov/museum-collections/commit/7585f0dd9fab84890768f8e6d5de31e0d0ab912c did it.
