### ISSUE TITLE
Attachments folder isn't created during conversion of cm:content to ucm:artifact

### ISSUE THREAD

**Issue by DmitryAlexandrov** [gdavydov/museum-collections#27]
Attachments folder path is "system/artifact_attachments/&lt;artistName&gt;/&lt;artifactName&gt;".
When ucm:artifact is being created from cm:content it have no artist name set.
So artifact attachments folder isn't created, and attachments can't be uploaded as a result.

**Comment by gdavydov** [comment]
Hi Dima, 

Need to modify UCMInheritProperiestargetAspect

something like this

```
protected void processNode(NodeRef nodeRef) {
    for (NodeRef parentRef = getParentNodeRef(nodeRef); parentRef != null; parentRef = getParentNodeRef(parentRef)) {
        boolean isParentValidSource = this.getNodeService().getAspects(parentRef)
                .contains(UCMConstants.ASPECT_INHERIT_PROPERTIES_SOURCE_QNAME);
        if (isParentValidSource) {
            this.getUtils().synchronizeUCMPropertyValues(parentRef, nodeRef);
            break;
        }

        (new UCMGenericFilter()).getOrCreateArtistMediaFolder(nodeRef);
    }
}
```

and make getOrCreateArtistMediaFolder public method

What do you think?

Do you want me put it as a bug?

**Comment by DmitryAlexandrov** [comment]
Such approach may help in some cases. But the root problem remains.
By allowing user to convert arbitrary image to artifact we allow him to create artifact without artist name set.
And if we don't have artist name we can't create folder for attachments.
Most simple solution I see is to use random UUID instead of "&lt;artistName&gt;/&lt;artifactName&gt;" as an attachment folder name.

**Comment by gdavydov** [comment]
OK, 

In this case there will 2 approaches.

First approach, when image get converted and parent artist exists - create attachment folder.

Second when parent artist folder do not exists - use random UUID.

Want to talk about it? I am available after 4 pm EST

**Comment by DmitryAlexandrov** [comment]
Fixed in commit https://github.com/gdavydov/museum-collections/commit/a34026cf045e536fd2300998f5e2acc8af2268f7
