### ISSUE TITLE
Related objects -- links

### ISSUE THREAD

**Issue by gdavydov** [gdavydov/museum-collections#35]
In Related objects instead of URL need to show the name

![screen shot 2016-03-28 at 3 40 57 pm](https://cloud.githubusercontent.com/assets/3901619/14088133/c8d02da2-f4fb-11e5-9099-b9004eff959b.png)

**Comment by DmitryAlexandrov** [comment]
Which name should be used?

**Comment by gdavydov** [comment]
Let’s talk today may be around 2 EST?

Also another thing i would like to discuss

Thank you

Greg

**Comment by DmitryAlexandrov** [comment]
Okay

> Let’s talk today may be around 2 EST?
> 
> Also another thing i would like to discuss
> 
> Thank you
> 
> Greg
