### ISSUE TITLE
Cnage zoom functionality back to Loope (magnifying glass)

### ISSUE THREAD

**Issue by gdavydov** [gdavydov/museum-collections#40]
Some people complain, that current soon functionality bit confusing.

Need to change back to the 'loope'. The same of the code still in ftp file. Please do not remove the current functionality, but jut comment it out.

**Comment by gdavydov** [comment]
'zoom" functionality sometimes complete disappear. Instead of zoom, it creates opaque square.

http://share.artium-gallery.com:8080/share/page/site/museum-test-site/artifact-details?nodeRef=workspace://SpacesStore/03b29146-ef13-4037-91cb-74127856ee7b

Looks like ti depends on image resolution

May be better do it like this?

http://thecodeplayer.com/walkthrough/magnifying-glass-for-images-using-jquery-and-css3

**Comment by DmitryAlexandrov** [comment]
That's how jquery.loupe works. It doesn't actually zoom image. It only shows fragment of image in original resolution.
It is assumed that preview image is smaller than original image. Which isn't our case.
We may use "Lens Zoom" from http://www.elevateweb.co.uk/image-zoom/examples
