### ISSUE TITLE
Document library contains links to "document-details" page instead of "artifact-details" when gallery mode is selected

### ISSUE THREAD

**Issue by DmitryAlexandrov** [gdavydov/museum-collections#7]

**Comment by DmitryAlexandrov** [comment]
Not reproduced in latest version.

**Comment by gdavydov** [comment]
It  come back. Plus header has options which were removed before.
![new header menu came back](https://cloud.githubusercontent.com/assets/3901619/12405676/379d7e84-be14-11e5-850f-cab94c9c432a.png)

**Comment by DmitryAlexandrov** [comment]
Not reproduced in last version.
